# Generated by Django 3.0.2 on 2020-12-13 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Solo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('nik', models.CharField(max_length=100)),
                ('provinisi', models.CharField(max_length=100)),
                ('tujuan', models.CharField(max_length=100)),
                ('naik', models.CharField(max_length=100)),
                ('turun', models.CharField(max_length=100)),
                ('tgl_naik', models.DateField()),
                ('tgl_turun', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('tlp', models.BigIntegerField()),
                ('konfirmasi', models.CharField(choices=[('waiting', 'Menunggu Konfirmasi'), ('confirmed', 'Sudah dikonfirmasi'), ('not_confirmed', 'Tidak dikonfirmasi')], default='waiting', max_length=100)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_solo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_pendaki', models.IntegerField()),
                ('nama', models.CharField(max_length=100)),
                ('nik', models.CharField(max_length=100)),
                ('provinisi', models.CharField(max_length=100)),
                ('tujuan', models.CharField(max_length=100)),
                ('naik', models.CharField(max_length=100)),
                ('turun', models.CharField(max_length=100)),
                ('tgl_naik', models.DateField()),
                ('tgl_turun', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('tlp', models.BigIntegerField()),
                ('konfirmasi', models.CharField(choices=[('waiting', 'Menunggu Konfirmasi'), ('confirmed', 'Sudah dikonfirmasi'), ('not_confirmed', 'Tidak dikonfirmasi')], default='waiting', max_length=100)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_group', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
