# Generated by Django 3.0.2 on 2020-12-14 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gunung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=100)),
                ('thumbnail', models.ImageField(default='/posyandu3.jpg', upload_to='documents/')),
                ('isi', models.TextField()),
                ('upload', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
