# Generated by Django 3.0.2 on 2020-12-14 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gunung', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gunung',
            name='thumbnail',
            field=models.ImageField(default='/static/img/123.jpg', upload_to='documents/'),
        ),
    ]
